name: ares_bridge
description: Flutter plugin for USB peer discovery and checksum-verified bidirectional file transfer for all platforms.
version: 0.0.2
homepage: https://aresdefencelabs.com/
repository: https://github.com/Ares-Defence-Labs/ares_bridge
issue_tracker: https://github.com/Ares-Defence-Labs/ares_bridge/issues
documentation: https://github.com/Ares-Defence-Labs/ares_bridge/tree/main/ares_bridge/doc

topics:
  - usb
  - file-transfer
  - android
  - macos
  - ios

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.12.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ares_bridge
        pluginClass: AresBridgePlugin
      ios:
        pluginClass: AresBridgePlugin
      linux:
        pluginClass: AresBridgePlugin
      macos:
        pluginClass: AresBridgePlugin
      windows:
        pluginClass: AresBridgePlugin
      web:
        pluginClass: AresBridgeWeb
        fileName: ares_bridge_web.dart
