name: ares_bridge
description: Cross-platform USB peer discovery and bidirectional file transfer.
version: 0.0.1
homepage: https://aresdefencelabs.com/

environment:
  sdk: ^3.12.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ares_bridge
        pluginClass: AresBridgePlugin
      ios:
        pluginClass: AresBridgePlugin
      linux:
        pluginClass: AresBridgePlugin
      macos:
        pluginClass: AresBridgePlugin
      windows:
        pluginClass: AresBridgePlugin
      web:
        pluginClass: AresBridgeWeb
        fileName: ares_bridge_web.dart
